#!/bin/sh

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

# Nitrux VxM - Static VFIO Override Script

PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

# -- DEBUG: Print to console.

echo "[VxM-DEBUG] Checking for Static Binding..." > /dev/console


# -- Check if the "Static Bind" trigger file exists on the real root filesystem.

if [ -z "${rootmnt}" ]; then
    rootmnt="/root"
fi

TRIGGER="${rootmnt}/etc/vxm/static-bind-enabled"

if [ ! -f "$TRIGGER" ]; then
    echo "[VxM-DEBUG] Trigger file not found at $TRIGGER" > /dev/console
    exit 0
fi

echo "[VxM-DEBUG] Trigger found! Seizing secondary GPUs..." > /dev/console

modprobe -v vfio-pci > /dev/console 2>&1

find /sys/devices/pci* -name boot_vga -exec sh -c '
  i="$1"
  GPU="${i%/*}"
  AUDIO="${GPU%.0}.1"

  # If boot_vga is 0 (Secondary GPU)
  if grep -q 0 "$i"; then
    echo "[VxM-DEBUG] Binding $GPU to vfio-pci" > /dev/console
    echo "vfio-pci" > "$GPU"/driver_override
    if [ -d "$AUDIO" ]; then
        echo "vfio-pci" > "$AUDIO"/driver_override
    fi
    
    # Force re-probe to make the override take effect
    echo "$GPU" > /sys/bus/pci/drivers_probe
  fi
' sh {} \;

echo "[VxM-DEBUG] Static Binding Complete." > /dev/console
