#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2026 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -e


# -- Functions.

append_if_not_present() {
    local file="$1"
    local line="$2"

    # Create file if it doesn't exist
    touch "$file"

    # Only append if line doesn't already exist
    if ! grep -qxF "$line" "$file" 2>/dev/null; then
        echo "$line" >> "$file"
    fi
}

[ -d /etc/initramfs-tools ] || mkdir -p /etc/initramfs-tools
[ -d /etc/modules-load.d ] || mkdir -p /etc/modules-load.d


# -- Add vfio modules to /etc/initramfs-tools/modules (avoid duplicates).

modules_file="/etc/initramfs-tools/modules"
append_if_not_present "$modules_file" "vfio"
append_if_not_present "$modules_file" "vfio_iommu_type1"
append_if_not_present "$modules_file" "vfio_virqfd"
append_if_not_present "$modules_file" "vfio_pci"


# -- Add vfio modules to /etc/modules-load.d/vfio-modules-config.conf to load at boot time.

modules_load_file="/etc/modules-load.d/vfio-modules-config.conf"
append_if_not_present "$modules_load_file" "vfio"
append_if_not_present "$modules_load_file" "vfio_iommu_type1"
append_if_not_present "$modules_load_file" "vfio_pci"


# -- Update initramfs.

echo "Updating initramfs..."
update-initramfs -u
