#!/bin/sh
set -e

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# Add VFIO modules to initramfs for early loading
manual_add_modules vfio
manual_add_modules vfio_iommu_type1
manual_add_modules vfio_virqfd
manual_add_modules vfio_pci
